//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace IntegracionRosado.WS_PO_PEDIDO_PEN_SAP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_OrdenesPendientes_OUT_SYNCBinding", Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class SI_OrdenesPendientes_OUT_SYNCService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_OrdenesPendientes_OUT_SYNCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_OrdenesPendientes_OUT_SYNCService() {
            this.Url = global::IntegracionRosado.Properties.Settings.Default.IntegracionRosado_WS_PO_PEDIDO_PEN_SAP_SI_OrdenesPendientes_OUT_SYNCService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_OrdenesPendientes_OUT_SYNCCompletedEventHandler SI_OrdenesPendientes_OUT_SYNCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MT_OrdenesPendientes_Response", Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
        public DT_OrdenesPendientes_Response SI_OrdenesPendientes_OUT_SYNC([System.Xml.Serialization.XmlElementAttribute(Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")] DT_OrdenesPendientes_Request MT_OrdenesPendientes_Request) {
            object[] results = this.Invoke("SI_OrdenesPendientes_OUT_SYNC", new object[] {
                        MT_OrdenesPendientes_Request});
            return ((DT_OrdenesPendientes_Response)(results[0]));
        }
        
        /// <remarks/>
        public void SI_OrdenesPendientes_OUT_SYNCAsync(DT_OrdenesPendientes_Request MT_OrdenesPendientes_Request) {
            this.SI_OrdenesPendientes_OUT_SYNCAsync(MT_OrdenesPendientes_Request, null);
        }
        
        /// <remarks/>
        public void SI_OrdenesPendientes_OUT_SYNCAsync(DT_OrdenesPendientes_Request MT_OrdenesPendientes_Request, object userState) {
            if ((this.SI_OrdenesPendientes_OUT_SYNCOperationCompleted == null)) {
                this.SI_OrdenesPendientes_OUT_SYNCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_OrdenesPendientes_OUT_SYNCOperationCompleted);
            }
            this.InvokeAsync("SI_OrdenesPendientes_OUT_SYNC", new object[] {
                        MT_OrdenesPendientes_Request}, this.SI_OrdenesPendientes_OUT_SYNCOperationCompleted, userState);
        }
        
        private void OnSI_OrdenesPendientes_OUT_SYNCOperationCompleted(object arg) {
            if ((this.SI_OrdenesPendientes_OUT_SYNCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_OrdenesPendientes_OUT_SYNCCompleted(this, new SI_OrdenesPendientes_OUT_SYNCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_Request {
        
        private DT_OrdenesPendientes_RequestItem[] iT_BEDATField;
        
        private DT_OrdenesPendientes_RequestItem1[] iT_MATNRField;
        
        private DT_OrdenesPendientes_RequestItem2[] iT_WERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_OrdenesPendientes_RequestItem[] IT_BEDAT {
            get {
                return this.iT_BEDATField;
            }
            set {
                this.iT_BEDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_OrdenesPendientes_RequestItem1[] IT_MATNR {
            get {
                return this.iT_MATNRField;
            }
            set {
                this.iT_MATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_OrdenesPendientes_RequestItem2[] IT_WERKS {
            get {
                return this.iT_WERKSField;
            }
            set {
                this.iT_WERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_RequestItem {
        
        private string bEDATField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEDAT {
            get {
                return this.bEDATField;
            }
            set {
                this.bEDATField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_Response {
        
        private DT_OrdenesPendientes_ResponseItem[] t_OC_PENDIENTEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_OrdenesPendientes_ResponseItem[] T_OC_PENDIENTE {
            get {
                return this.t_OC_PENDIENTEField;
            }
            set {
                this.t_OC_PENDIENTEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_ResponseItem {
        
        private string eBELNField;
        
        private string eBELPField;
        
        private string mATNRField;
        
        private string eINDTField;
        
        private string mENGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELN {
            get {
                return this.eBELNField;
            }
            set {
                this.eBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EBELP {
            get {
                return this.eBELPField;
            }
            set {
                this.eBELPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EINDT {
            get {
                return this.eINDTField;
            }
            set {
                this.eINDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_RequestItem1 {
        
        private string mATNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:elrosado.com:jda:asr:OrdenesPendientes")]
    public partial class DT_OrdenesPendientes_RequestItem2 {
        
        private string wERKSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void SI_OrdenesPendientes_OUT_SYNCCompletedEventHandler(object sender, SI_OrdenesPendientes_OUT_SYNCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_OrdenesPendientes_OUT_SYNCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_OrdenesPendientes_OUT_SYNCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OrdenesPendientes_Response Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OrdenesPendientes_Response)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591