//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegracionRosado.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piqas.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderS" +
            "ervice=BS_KIOSKO_TIENDA_PIQ&receiverParty=&receiverService=&interface=SI_Centro_" +
            "OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Anuo%3AkioskoTienda%3Acentro")]
        public string IntegracionRosado_WS_CENTRO_SI_Centro_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_CENTRO_SI_Centro_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piqas.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderS" +
            "ervice=BS_JDA_ASR_PIQ&receiverParty=&receiverService=&interface=SI_PromocionxArt" +
            "iculo_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Ajda%3Aasr%3APromocionxArt" +
            "iculo")]
        public string IntegracionRosado_WS_PROMOCION_SAP_SI_PromocionxArticulo_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_PROMOCION_SAP_SI_PromocionxArticulo_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://piprd.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty=&senderS" +
            "ervice=BS_JDA_ASR_PIP&receiverParty=&receiverService=&interface=SI_OrdenesPendie" +
            "ntes_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Ajda%3Aasr%3AOrdenesPendien" +
            "tes")]
        public string IntegracionRosado_WS_PEDIDO_PEN_SAP_SI_OrdenesPendientes_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_PEDIDO_PEN_SAP_SI_OrdenesPendientes_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vhcerpipci.hec.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty" +
            "=&senderService=BS_JDA_ASR_PIP&receiverParty=&receiverService=&interface=SI_Orde" +
            "nesPendientes_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Ajda%3Aasr%3AOrden" +
            "esPendientes")]
        public string IntegracionRosado_WS_PO_PEDIDO_PEN_SAP_SI_OrdenesPendientes_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_PO_PEDIDO_PEN_SAP_SI_OrdenesPendientes_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vhcerpipci.hec.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty" +
            "=&senderService=BS_JDA_ASR_PIP&receiverParty=&receiverService=&interface=SI_Prom" +
            "ocionxArticulo_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Ajda%3Aasr%3AProm" +
            "ocionxArticulo")]
        public string IntegracionRosado_WS_PO_PROMOCION_SAP_SI_PromocionxArticulo_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_PO_PROMOCION_SAP_SI_PromocionxArticulo_OUT_SYNCService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://vhcerpipci.hec.elrosado.com:50000/XISOAPAdapter/MessageServlet?senderParty" +
            "=&senderService=BS_KIOSKO_TIENDA_PIP&receiverParty=&receiverService=&interface=S" +
            "I_Centro_OUT_SYNC&interfaceNamespace=urn%3Aelrosado.com%3Anuo%3AkioskoTienda%3Ac" +
            "entro")]
        public string IntegracionRosado_WS_PO_CENTROS_SI_Centro_OUT_SYNCService {
            get {
                return ((string)(this["IntegracionRosado_WS_PO_CENTROS_SI_Centro_OUT_SYNCService"]));
            }
        }
    }
}
